# Generated by Django 4.2.27 on 2025-12-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(max_length=50)),
                (
                    "owner",
                    models.CharField(
                        choices=[("Customer", "Customer"), ("Preh", "Preh")],
                        max_length=50,
                    ),
                ),
                (
                    "eq_number",
                    models.CharField(max_length=50, verbose_name="Equipment Number"),
                ),
                ("power_supply", models.CharField(max_length=100)),
                ("power_kw", models.CharField(blank=True, max_length=20)),
                ("air_supply_bar", models.CharField(default="no", max_length=20)),
                ("air_supply_diam", models.CharField(default="no", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Equipment",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ValidationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Validation Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ValidationChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_iatf",
                    models.CharField(max_length=100, verbose_name="IATF Reference"),
                ),
                (
                    "ref_vda",
                    models.CharField(max_length=100, verbose_name="VDA Reference"),
                ),
                ("test", models.TextField(verbose_name="Test Description")),
                ("expected", models.TextField(verbose_name="Expected Result")),
                ("example", models.TextField(blank=True, verbose_name="Example")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.validationcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="ValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOK", "NOK")], max_length=3
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now=True)),
                ("validated_by", models.CharField(blank=True, max_length=100)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.validationchecklistitem",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_results",
                        to="core.equipment",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "checklist_item__category__order",
                    "checklist_item__order",
                ],
                "unique_together": {("equipment", "checklist_item")},
            },
        ),
    ]
