# Generated by Django 4.2.27 on 2025-12-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="photo_front",
            field=models.URLField(blank=True, verbose_name="Front Photo URL"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="photo_tag",
            field=models.URLField(blank=True, verbose_name="Tag Photo URL"),
        ),
        migrations.CreateModel(
            name="EquipmentDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(max_length=100, verbose_name="Equipment Type"),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="core.equipment",
                    ),
                ),
            ],
            options={
                "ordering": ["equipment__id", "id"],
            },
        ),
    ]
