# Generated by Django 4.2.27 on 2025-12-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_equipment_photo_front_equipment_photo_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentdevice",
            name="device_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Equipment Type"
            ),
        ),
        migrations.AlterField(
            model_name="equipmentdevice",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name="equipmentdevice",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
