# Generated by Django 4.2.27 on 2025-12-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_equipmentdevice_device_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("title_key", models.CharField(max_length=50)),
                ("desc_key", models.CharField(blank=True, max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_highlighted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Documentation Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DocumentationChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_key", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.documentationcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="DocumentationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_checked", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checklist_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.documentationchecklistitem",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentation_results",
                        to="core.equipment",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "checklist_item__category__order",
                    "checklist_item__order",
                ],
                "unique_together": {("equipment", "checklist_item")},
            },
        ),
    ]
