# Generated by Django 4.2.27 on 2025-12-11 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_documentationcategory_documentationchecklistitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BomItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station", models.CharField(max_length=100)),
                (
                    "part_number",
                    models.CharField(
                        max_length=100, verbose_name="Material/Part Number"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "visual_aid_bg_color",
                    models.CharField(default="#CCFFFF", max_length=7),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="bom_images/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "station"],
            },
        ),
        migrations.CreateModel(
            name="DocHistoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("register", models.CharField(max_length=100)),
                ("changes", models.TextField()),
                ("created_by", models.CharField(max_length=100)),
                ("date_created", models.DateField()),
                ("released_by", models.CharField(max_length=100)),
                ("date_released", models.DateField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#bdd7ee", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BomItemVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_applicable", models.BooleanField(default=False)),
                (
                    "bom_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_variants",
                        to="core.bomitem",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_items",
                        to="core.variant",
                    ),
                ),
            ],
            options={
                "unique_together": {("bom_item", "variant")},
            },
        ),
        migrations.AddField(
            model_name="bomitem",
            name="variants",
            field=models.ManyToManyField(
                related_name="bom_items",
                through="core.BomItemVariant",
                to="core.variant",
            ),
        ),
    ]
