# Generated by Django 4.2.27 on 2025-12-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_bomitem_dochistoryitem_variant_bomitemvariant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="height",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Inaltime [mm]"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="length",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Lungime [mm]"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="weight",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Greutate [kg]"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="width",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Latime [mm]"
            ),
        ),
    ]
